// ─── Developer Documentation Frameworks Configuration ───────────────────────
// تعريف الـ 10 frameworks المدعومة مع إعدادات الزحف والمعالجة

export const FRAMEWORKS = [
  {
    id: "laravel",
    name: "Laravel",
    icon: "🔴",
    version: "12",
    docsUrl: "https://laravel.com/docs",
    category: "backend",
    crawlConfig: {
      baseUrl: "https://laravel.com/docs/12.x/installation",
      linkSelector: 'a[href*="/docs/12.x/"]',
      contentSelector: ".docs-content, article, main, .content",
      excludeSelectors: ["nav", "footer", ".sidebar", ".header", "script", "style"],
      maxPages: 200,
      seedUrls: [
        // Prologue
        "https://laravel.com/docs/12.x/releases",
        "https://laravel.com/docs/12.x/upgrade",
        "https://laravel.com/docs/12.x/contributions",
        // Getting Started
        "https://laravel.com/docs/12.x/installation",
        "https://laravel.com/docs/12.x/configuration",
        "https://laravel.com/docs/12.x/structure",
        "https://laravel.com/docs/12.x/frontend",
        "https://laravel.com/docs/12.x/starter-kits",
        "https://laravel.com/docs/12.x/deployment",
        // Architecture
        "https://laravel.com/docs/12.x/lifecycle",
        "https://laravel.com/docs/12.x/container",
        "https://laravel.com/docs/12.x/providers",
        "https://laravel.com/docs/12.x/facades",
        // The Basics
        "https://laravel.com/docs/12.x/routing",
        "https://laravel.com/docs/12.x/middleware",
        "https://laravel.com/docs/12.x/csrf",
        "https://laravel.com/docs/12.x/controllers",
        "https://laravel.com/docs/12.x/requests",
        "https://laravel.com/docs/12.x/responses",
        "https://laravel.com/docs/12.x/views",
        "https://laravel.com/docs/12.x/blade",
        "https://laravel.com/docs/12.x/vite",
        "https://laravel.com/docs/12.x/urls",
        "https://laravel.com/docs/12.x/session",
        "https://laravel.com/docs/12.x/validation",
        "https://laravel.com/docs/12.x/errors",
        "https://laravel.com/docs/12.x/logging",
        // Digging Deeper
        "https://laravel.com/docs/12.x/artisan",
        "https://laravel.com/docs/12.x/broadcasting",
        "https://laravel.com/docs/12.x/cache",
        "https://laravel.com/docs/12.x/collections",
        "https://laravel.com/docs/12.x/concurrency",
        "https://laravel.com/docs/12.x/context",
        "https://laravel.com/docs/12.x/contracts",
        "https://laravel.com/docs/12.x/events",
        "https://laravel.com/docs/12.x/filesystem",
        "https://laravel.com/docs/12.x/helpers",
        "https://laravel.com/docs/12.x/http-client",
        "https://laravel.com/docs/12.x/localization",
        "https://laravel.com/docs/12.x/mail",
        "https://laravel.com/docs/12.x/notifications",
        "https://laravel.com/docs/12.x/packages",
        "https://laravel.com/docs/12.x/processes",
        "https://laravel.com/docs/12.x/queues",
        "https://laravel.com/docs/12.x/rate-limiting",
        "https://laravel.com/docs/12.x/strings",
        "https://laravel.com/docs/12.x/scheduling",
        // Security
        "https://laravel.com/docs/12.x/authentication",
        "https://laravel.com/docs/12.x/authorization",
        "https://laravel.com/docs/12.x/encryption",
        "https://laravel.com/docs/12.x/hashing",
        "https://laravel.com/docs/12.x/passwords",
        // Database
        "https://laravel.com/docs/12.x/database",
        "https://laravel.com/docs/12.x/queries",
        "https://laravel.com/docs/12.x/pagination",
        "https://laravel.com/docs/12.x/migrations",
        "https://laravel.com/docs/12.x/seeding",
        "https://laravel.com/docs/12.x/redis",
        // Eloquent ORM
        "https://laravel.com/docs/12.x/eloquent",
        "https://laravel.com/docs/12.x/eloquent-relationships",
        "https://laravel.com/docs/12.x/eloquent-collections",
        "https://laravel.com/docs/12.x/eloquent-mutators",
        "https://laravel.com/docs/12.x/eloquent-resources",
        "https://laravel.com/docs/12.x/eloquent-serialization",
        "https://laravel.com/docs/12.x/eloquent-factories",
        // Testing
        "https://laravel.com/docs/12.x/testing",
        "https://laravel.com/docs/12.x/http-tests",
        "https://laravel.com/docs/12.x/console-tests",
        "https://laravel.com/docs/12.x/dusk",
        "https://laravel.com/docs/12.x/mocking",
      ],
    },
    keywords: ["laravel", "eloquent", "blade", "artisan", "migration", "middleware", "route"],
  },
  {
    id: "react",
    name: "React",
    icon: "⚛️",
    version: "19",
    docsUrl: "https://react.dev",
    category: "frontend",
    crawlConfig: {
      baseUrl: "https://react.dev/learn",
      linkSelector: 'a[href^="/learn"], a[href^="/reference"]',
      contentSelector: "article, main, .content",
      excludeSelectors: ["nav", "footer", "aside", "script", "style"],
      maxPages: 300,
    },
    keywords: ["react", "hooks", "useState", "useEffect", "component", "jsx", "props"],
  },
  {
    id: "nextjs",
    name: "Next.js",
    icon: "▲",
    version: "15",
    docsUrl: "https://nextjs.org/docs",
    category: "frontend",
    crawlConfig: {
      baseUrl: "https://nextjs.org/docs",
      linkSelector: 'a[href^="/docs"]',
      contentSelector: "article, main, .docs-content",
      excludeSelectors: ["nav", "footer", "aside", "script", "style"],
      maxPages: 250,
    },
    keywords: ["nextjs", "next.js", "app router", "pages", "server component", "ssr", "middleware"],
  },
  {
    id: "nodejs",
    name: "Node.js",
    icon: "🟢",
    version: "22",
    docsUrl: "https://nodejs.org/docs",
    category: "backend",
    crawlConfig: {
      baseUrl: "https://nodejs.org/docs/latest/api/",
      linkSelector: 'a[href$=".html"], a[href*="/api/"]',
      contentSelector: "#apicontent, main, .content",
      excludeSelectors: ["nav", "footer", "#toc", "script", "style"],
      maxPages: 150,
    },
    keywords: ["nodejs", "node.js", "express", "npm", "fs", "http", "stream", "buffer"],
  },
  {
    id: "python",
    name: "Python",
    icon: "🐍",
    version: "3.12",
    docsUrl: "https://docs.python.org/3",
    category: "backend",
    crawlConfig: {
      baseUrl: "https://docs.python.org/3/library/index.html",
      linkSelector: 'a[href$=".html"]',
      contentSelector: ".body, .document, .section",
      excludeSelectors: ["nav", ".sphinxsidebar", "footer", "script", "style"],
      maxPages: 400,
      seedUrls: [
        "https://docs.python.org/3/tutorial/index.html",
        "https://docs.python.org/3/reference/index.html",
        "https://docs.python.org/3/howto/index.html",
      ],
    },
    keywords: ["python", "pip", "async", "decorator", "class", "list", "dict", "import"],
  },
  {
    id: "fastapi",
    name: "FastAPI",
    icon: "⚡",
    version: "0.115",
    docsUrl: "https://fastapi.tiangolo.com",
    category: "backend",
    crawlConfig: {
      baseUrl: "https://fastapi.tiangolo.com/tutorial",
      linkSelector: 'a[href*="/tutorial/"], a[href*="/advanced/"], a[href*="/reference/"]',
      contentSelector: "article, .md-content, main",
      excludeSelectors: ["nav", "footer", "header", "script", "style"],
      maxPages: 150,
    },
    keywords: ["fastapi", "pydantic", "uvicorn", "endpoint", "dependency injection", "api"],
  },
  {
    id: "django",
    name: "Django",
    icon: "🟩",
    version: "5.1",
    docsUrl: "https://docs.djangoproject.com",
    category: "backend",
    crawlConfig: {
      baseUrl: "https://docs.djangoproject.com/en/5.1/topics",
      linkSelector:
        'a[href*="/en/5.1/topics/"], a[href*="/en/5.1/ref/"], a[href*="/en/5.1/howto/"]',
      contentSelector: "#docs-content, .document, .section",
      excludeSelectors: ["nav", "footer", "#doc-sidebar", "script", "style"],
      maxPages: 300,
    },
    keywords: ["django", "orm", "model", "view", "template", "urlconf", "admin", "middleware"],
  },
  {
    id: "docker",
    name: "Docker",
    icon: "🐳",
    version: "latest",
    docsUrl: "https://docs.docker.com",
    category: "devops",
    crawlConfig: {
      baseUrl: "https://docs.docker.com/get-started",
      linkSelector: 'a[href*="/get-started/"], a[href*="/engine/"], a[href*="/compose/"]',
      contentSelector: "article, main, .content",
      excludeSelectors: ["nav", "footer", "aside", "script", "style"],
      maxPages: 200,
    },
    keywords: ["docker", "container", "dockerfile", "docker-compose", "image", "volume", "network"],
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    icon: "☸️",
    version: "1.31",
    docsUrl: "https://kubernetes.io/docs",
    category: "devops",
    crawlConfig: {
      baseUrl: "https://kubernetes.io/docs/concepts",
      linkSelector: 'a[href*="/docs/concepts/"], a[href*="/docs/tasks/"]',
      contentSelector: "main, .td-content, article",
      excludeSelectors: ["nav", "footer", ".sidebar", "script", "style"],
      maxPages: 250,
    },
    keywords: ["kubernetes", "k8s", "pod", "deployment", "service", "kubectl", "helm", "ingress"],
  },
  {
    id: "git",
    name: "Git",
    icon: "📦",
    version: "latest",
    docsUrl: "https://git-scm.com/docs",
    category: "devops",
    crawlConfig: {
      baseUrl: "https://git-scm.com/book/en/v2",
      linkSelector: 'a[href*="/book/en/v2/"], a[href*="/docs/"]',
      contentSelector: "#main, .book-content, .man-content, .sect1",
      excludeSelectors: ["nav", "footer", "header", "script", "style"],
      maxPages: 150,
    },
    keywords: ["git", "commit", "branch", "merge", "rebase", "remote", "stash", "push", "pull"],
  },
];

export function getFrameworkById(id) {
  return FRAMEWORKS.find((f) => f.id === id) || null;
}

export function getFrameworksByCategory(category) {
  return FRAMEWORKS.filter((f) => f.category === category);
}

export const CATEGORIES = [
  { id: "frontend", name: "Frontend", icon: "🖥️" },
  { id: "backend", name: "Backend", icon: "⚙️" },
  { id: "devops", name: "DevOps", icon: "🚀" },
];
